### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by TheRedBull205** [jeroenterheerdt/MQTTLocationTracker#2]
Hi, i am using this for home assistant it works great so far but it really need some improvements:
1. Connect automatic on program startup.
2. Hidden service on windows startup.
3. Let the user choose to use windows or usb device(if possible) like:
    - VK-162 G-MOUSE
    - BU-353S4 SiRF Star IV
    - etc,
    Since windows isn't really giving you a choice wich one you should use.

**Comment by jeroenterheerdt** [comment]
Go ahead, implement it. I do no longer use this myself.
